### ISSUE TITLE
What are the steps for 2018?

### ISSUE THREAD

**Issue by Boscop** [rajanski/postgresql_postgis-on-uberspace#3]
These instructions for installing PostGIS on Uberspace are from 2014.
What are the steps for 2018 to install PostGIS on Uberspace 6? :)
(Uberspace 7 doesn't support Postgres yet.)

I want to install the latest version of PostGIS that is supported by the Postgres version on Uberspace.

**Comment by manstze** [comment]
For me It would also be great to update the readme. There is a manual to install PostgreSQL on Uberspace 7:
https://lab.uberspace.de/guide_postgresql.html

I managed to install PostgreSQL 11.5, GEOS 3.7.2, PROJ 6.1.1 and PostGIS 2.5.3 on Uberspace 7 (see code below). But I fail to activate PostGIS in PostgreSQL. 
I think the problem is somehow connected to  LD_LIBRARY_PATH / lib path. It would be great if you could specify what's happening there.


--------------------------------------------------------------------------------------------------------------------------
`
## GEOS
wget http://download.osgeo.org/geos/geos-3.7.2.tar.bz2
tar xvjf geos-3.7.2.tar.bz2
cd geos-3.7.2
./configure --prefix=$HOME/opt/geos/build --enable-python
make 
make install
cd ..

## PROJ

wget http://download.osgeo.org/proj/proj-6.1.1.tar.gz
tar xvzf proj-6.1.1.tar.gz
cd proj-6.1.1
./configure --prefix=$HOME/opt/proj
make && make install
cd ..


## GDAL

wget http://download.osgeo.org/gdal/3.0.1/gdal-3.0.1.tar.gz
tar xvzf gdal-3.0.1.tar.gz
cd gdal-3.0.1
./configure --prefix=$HOME/opt/gdal --with-proj=$HOME/opt/proj --with-pg=$HOME/opt/postgresql --enable-python
make && make install
cd ..


## PostGIS
wget http://download.osgeo.org/postgis/source/postgis-2.5.3.tar.gz

tar xvzf postgis-2.5.3.tar.gz
cd postgis-2.5.3

./configure --with-projdir=$HOME/opt/proj \
--with-geosconfig=$HOME/opt/geos/build/bin/geos-config \
--with-gdalconfig=$HOME/opt/gdal/bin/gdal-config
mkdir $HOME/opt/postgis
make && make install DESTDIR=$HOME/opt/postgis REGRESS=1
cd ..`

**Comment by rajanski** [comment]
Can you pls post what the error message is when you execute 'create
extension postgis'

manstze <notifications@github.com> schrieb am So., 18. Aug. 2019, 21:35:

**Comment by manstze** [comment]
After executing 'create extension postgis' in pgAdmin4 I get this error message:

```
ERROR:  could not open extension control file "/home/manstze/opt/postgresql/share/extension/postgis.control": Datei oder Verzeichnis nicht gefunden
SQL state: 58P01
```

Further Details:
First I create a SSH - Tunnel like it is described for [MySQL](https://manual.uberspace.de/database-mysql.html) and adopted the standard port to 5432:
`ssh -L 3306:127.0.0.1:5432 eliza@dolittle.uberspace.de`

Then I add the database to pgadmin4.

**Comment by rajanski** [comment]
Uberspace now have their own postgresql / postgis installation script, see https://lab.uberspace.de/guide_postgresql.html
Be aware that postgis on centos doesnt include the protobuf-c library (which is needed for vector tiles)
